---
- name: ssh-keyscan for known_hosts file
  command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}
  register: keyscan

- name: input key
  lineinfile:
    path: ~/.ssh/known_hosts
    line: '{{ item }}'
    create: yes
  with_items:
    - '{{ keyscan.stdout_lines }}'

- name: ssh-keygen for authorized_keys file
  command: "ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ''"
  ignore_errors: yes
  run_once: true

- name: Install ssh pass
  become: true
  action: '{{ ansible_pkg_mgr }} name=sshpass'

- name: input key for each node
  connection: ssh
  authorized_key:
    user: rnd1
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
